# Generated by Django 3.0.5 on 2023-12-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_auto_20231207_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantity'),
        ),
    ]
