# Generated by Django 3.0.5 on 2023-12-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_auto_20231207_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
