# Generated by Django 3.0.5 on 2023-12-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0029_auto_20231207_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Toddlers', 'Toddlers'), ('Unisex', 'Unisex')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Order Placed', max_length=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Second Hand', 'Second Hand'), ('Shipped From Abroad', 'Shipped From Abroad'), ('Knighted', 'Knighted'), ('Locally Made', 'Locally Made')], max_length=50),
        ),
    ]
