# Generated by Django 3.0.5 on 2023-12-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0030_auto_20231207_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='status',
        ),
    ]
