# Generated by Django 3.0.5 on 2023-12-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0032_brand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Toddlers', 'Toddlers'), ('Unisex', 'Unisex')], default='Choose one below', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Second Hand', 'Second Hand'), ('Shipped From Abroad', 'Shipped From Abroad'), ('Knighted', 'Knighted'), ('Locally Made', 'Locally Made')], default='Choose One Below', max_length=50),
        ),
    ]
