# Generated by Django 3.0.5 on 2023-12-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0036_auto_20231207_2038'),
    ]

    operations = [
    ]
