# Generated by Django 3.0.5 on 2023-12-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0037_auto_20231207_2041'),
    ]

    operations = [
    ]
