# Generated by Django 5.0 on 2023-12-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0042_alter_brand_id_alter_category_id_alter_customer_id_and_more'),
    ]

    operations = [
    ]
