# Generated by Django 3.0.5 on 2023-12-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0043_auto_20231207_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('Abercrombie & Fitch', 'Abercrombie & Fitch'), ('Adidas', 'Adidas'), ('Adore Me', 'Adore Me'), ('Aerie', 'Aerie'), ('Altra', 'Altra'), ('American Apparel', 'American Apparel'), ('American Eagle Outfitters', 'American Eagle Outfitters'), ('Ann Taylor', 'Ann Taylor'), ('Anna Sui', 'Anna Sui'), ('Anne Klein', 'Anne Klein'), ('Anthropologie', 'Anthropologie'), ('Arden B.', 'Arden B.'), ('Ariat', 'Ariat'), ('Armani', 'Armani'), ('Asics', 'Asics'), ('Athleta', 'Athleta'), ('Avenue', 'Avenue'), ('Away', 'Away'), ('Aéropostale', 'Aéropostale'), ('BCBG', 'BCBG'), ('Banana Republic', 'Banana Republic'), ('Bealls', 'Bealls'), ('Bebe', 'Bebe'), ('Birkenstock', 'Birkenstock'), ('Bombas', 'Bombas'), ('Boohoo', 'Boohoo'), ('Born Shoes', 'Born Shoes'), ('Borsalino', 'Borsalino'), ('Brooks Brothers', 'Brooks Brothers'), ('Brooks Sports', 'Brooks Sports'), ('Burberry', 'Burberry'), ('C by Champion', 'C by Champion'), ('Calvin Klein', 'Calvin Klein'), ('Cartier', 'Cartier'), ('Catherines Plus Sizes', 'Catherines Plus Sizes'), ('Cato', 'Cato'), ('Champion', 'Champion'), ('Chanel', 'Chanel'), ('Charlotte Russe', 'Charlotte Russe'), ('Chicos', 'Chicos'), ('Christopher & Banks', 'Christopher & Banks'), ('Churchs', 'Churchs'), ('CitiTrends', 'CitiTrends'), ('Claires Accessories', 'Claires Accessories'), ('Clarks', 'Clarks'), ('Coach', 'Coach'), ('Columbia', 'Columbia'), ('Converse', 'Converse'), ('Crocs', 'Crocs'), ('DKNY', 'DKNY'), ('Dior', 'Dior'), ('Dockers', 'Dockers'), ('Dolce & Gabbana', 'Dolce & Gabbana'), ('Dr. Scholls shoes', 'Dr. Scholls shoes'), ('DressBarn', 'DressBarn'), ('Duluth Trading Co.', 'Duluth Trading Co.'), ('Dune', 'Dune'), ('Eddie Bauer', 'Eddie Bauer'), ('Everlane', 'Everlane'), ('Express', 'Express'), ('Fabletics', 'Fabletics'), ('Forever', 'Forever'), ('Fossil', 'Fossil'), ('Fruit of the Loom', 'Fruit of the Loom'), ('G-star', 'G-star'), ('Gap', 'Gap'), ('GapBody', 'GapBody'), ('Gloria Vanderbilt', 'Gloria Vanderbilt'), ('Goodys', 'Goodys'), ('Gucci', 'Gucci'), ('H&M', 'H&M'), ('Hanes', 'Hanes'), ('Hollister', 'Hollister'), ('Honey', 'Honey'), ('Hot Topic', 'Hot Topic'), ('Hugo Boss', 'Hugo Boss'), ('Hush Puppies', 'Hush Puppies'), ('Ivanka Trump (Brand)', 'Ivanka Trump (Brand)'), ('J. Jill', 'J. Jill'), ('J.Crew', 'J.Crew'), ('Jimmy Choo', 'Jimmy Choo'), ('Jos. A. Bank', 'Jos. A. Bank'), ('Juicy Couture', 'Juicy Couture'), ('K & G Fashion Superstore', 'K & G Fashion Superstore'), ('K-Swiss', 'K-Swiss'), ('Kate Spade', 'Kate Spade'), ('Kenneth Cole', 'Kenneth Cole'), ('KidSuper', 'KidSuper'), ('L. L. Bean', 'L. L. Bean'), ('LOFT', 'LOFT'), ('Lands End', 'Lands End'), ('Lane Bryant', 'Lane Bryant'), ('Lee', 'Lee'), ('Levis', 'Levis'), ('LifeStride', 'LifeStride'), ('Liz Claiborne', 'Liz Claiborne'), ('London Fog', 'London Fog'), ('Louis Vuitton', 'Louis Vuitton'), ('Lucy', 'Lucy'), ('Lululemon', 'Lululemon'), ('MVMT', 'MVMT'), ('Madewell', 'Madewell'), ('Marc Jacobs', 'Marc Jacobs'), ('Marmot', 'Marmot'), ('Maurices', 'Maurices'), ('Mens Wearhouse', 'Mens Wearhouse'), ('Merrell', 'Merrell'), ('Michael Kors', 'Michael Kors'), ('Mudd', 'Mudd'), ('Naturalizer', 'Naturalizer'), ('Nautica', 'Nautica'), ('New Balance', 'New Balance'), ('New Era', 'New Era'), ('New York & Company', 'New York & Company'), ('Nike', 'Nike'), ('Nine West', 'Nine West'), ('Oakley', 'Oakley'), ('Obey', 'Obey'), ('Old Navy', 'Old Navy'), ('Omega', 'Omega'), ('Oscar de La Renta', 'Oscar de La Renta'), ('PUMA', 'PUMA'), ('Pacific Sunwear', 'Pacific Sunwear'), ('Patagonia', 'Patagonia'), ('Polo Ralph Lauren', 'Polo Ralph Lauren'), ('Prada', 'Prada'), ('QUIZ', 'QUIZ'), ('Quiksilver', 'Quiksilver'), ('Ralph Lauren', 'Ralph Lauren'), ('RayBan', 'RayBan'), ('Red Wing Shoes', 'Red Wing Shoes'), ('Reebok', 'Reebok'), ('Rockport', 'Rockport'), ('Rolex', 'Rolex'), ('Ryka', 'Ryka'), ('SOREL', 'SOREL'), ('Sam Edelman', 'Sam Edelman'), ('Samsonite', 'Samsonite'), ('Sean John', 'Sean John'), ('Seiko', 'Seiko'), ('Shape-ups', 'Shape-ups'), ('Skechers', 'Skechers'), ('Stitch Fix', 'Stitch Fix'), ('Stussy', 'Stussy'), ('Swarovski', 'Swarovski'), ('Swatch', 'Swatch'), ('TAG Heuer', 'TAG Heuer'), ('TUMI', 'TUMI'), ('Talbots', 'Talbots'), ('Ted Baker', 'Ted Baker'), ('Teva', 'Teva'), ('The Buckle', 'The Buckle'), ('The Limited', 'The Limited'), ('The North Face', 'The North Face'), ('Timberland', 'Timberland'), ('Tissot', 'Tissot'), ('Tommy Hilfiger', 'Tommy Hilfiger'), ('Tommy John', 'Tommy John'), ('Toms', 'Toms'), ('Torrid', 'Torrid'), ('True Religion', 'True Religion'), ('UGG', 'UGG'), ('UNIQLO', 'UNIQLO'), ('Under Armour', 'Under Armour'), ('Urban Outfitters', 'Urban Outfitters'), ('VS Pink', 'VS Pink'), ('Van Heusen', 'Van Heusen'), ('Vans', 'Vans'), ('Vera Wang', 'Vera Wang'), ('Versace', 'Versace'), ('Victorias Secret', 'Victorias Secret'), ('Victorinox Swiss Army', 'Victorinox Swiss Army'), ('Vince Camuto', 'Vince Camuto'), ('Vineyard Vines', 'Vineyard Vines'), ('Wet Seal', 'Wet Seal'), ('White House Black Market', 'White House Black Market'), ('Wilson Sporting Goods', 'Wilson Sporting Goods'), ('Wilsons Leather', 'Wilsons Leather'), ('Wolverine', 'Wolverine'), ('Wrangler', 'Wrangler'), ('Yves Saint Laurent', 'Yves Saint Laurent'), ('Zara', 'Zara'), ('rue', 'rue')], default='Choose a brand Matching the product Below', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Second Hand', 'Second Hand'), ('Shipped From Abroad', 'Shipped From Abroad'), ('Knighted', 'Knighted'), ('Locally Made', 'Locally Made')], default='Choose One Below', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
